(() => {
  const FEEDS=[
    'https://raw.githubusercontent.com/XDSawyerLoL/LEFILLIBRE/main/feed.json',
    'https://xdsawyerlol.github.io/LEFILLIBRE/feed.json'
  ];
  const QUANTIC_NEWS_URL='https://xdsawyerlol.github.io/QuanticMinds/news.html';
  const grid=document.getElementById('news-grid');
  const updated=document.getElementById('news-updated');
  const filters=[...document.querySelectorAll('.news-filter')];
  if(!grid) return;
  let items=[]; let current='all';
  const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const ago=iso=>{const d=new Date(iso),m=Math.max(0,Math.round((Date.now()-d)/60000));if(m<60)return `${m} min`;const h=Math.floor(m/60);if(h<24)return `${h} h`;return d.toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})};
  const hay=i=>`${i.category||''} ${i.source||''} ${i.title||''} ${i.summary||''}`.toLowerCase();
  const techSource=i=>/01net|frandroid|numerama|techcrunch|the verge|wired|ars technica|zdnet|clubic|cnet|engadget|tom's hardware|les numériques|korben|macg|next\.ink|venturebeat/i.test(i.source||'');
  const eligible=i=>String(i.category||'').toLowerCase().includes('tech')||techSource(i)||/\bia\b|intelligence artificielle|artificial intelligence|openai|chatgpt|anthropic|gemini|mistral|robot|tech|numéri|logiciel|cyber|semi-conduct|cloud|ordinateur|smartphone|innovation|startup|internet|data|automatisation|quantique|puce|hardware|software|processeur|plateforme|application|iphone|android|windows|linux|apple|google|microsoft|nvidia|amd|intel|tesla|spacex/.test(hay(i));
  const match=(i,f)=>{const h=hay(i);if(f==='all')return true;if(f==='ai')return /\bia\b|intelligence artificielle|artificial intelligence|openai|chatgpt|anthropic|gemini|mistral|machine learning|modèle|agent|cloud|cyber|numéri|logiciel/.test(h);if(f==='robot')return /robot|robotique|androïde|humanoïde|automatisation|drone/.test(h);if(f==='product')return /produit|app|application|smartphone|iphone|android|ordinateur|navigateur|browser|logiciel|plateforme|device|nas|écran|puce|apple|google|microsoft|nvidia|amd|intel/.test(h);if(f==='future')return /innovation|futur|recherche|prototype|startup|laboratoire|quantique|espace|énergie|mobilité|spacex|tesla/.test(h);return true};
  const storyKey=i=>String(i.url||i.articleUrl||i.title||'');
  const storyUrl=i=>`${QUANTIC_NEWS_URL}?story=${encodeURIComponent(storyKey(i))}`;
  const externalSource=i=>{const u=String(i.url||'').trim();return u&&!/xdsawyerlol\.github\.io\/LEFILLIBRE/i.test(u)?u:''};
  const shareHref=i=>`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(storyUrl(i))}`;
  const deepLink=new URLSearchParams(location.search).get('story')||'';
  const focusDeepLink=()=>{if(!deepLink)return;const cards=[...grid.querySelectorAll('.news-card')];const target=cards.find(card=>card.dataset.story===deepLink);if(!target)return;target.classList.add('news-target');setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:'center'}),120)};
  const wireSmartShare=()=>{grid.querySelectorAll('[data-smart-share]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.story||'';const item=items.find(x=>storyKey(x)===key);if(!item)return;const smart=window.QuanticNewsSocial?.smartShare;if(smart)smart(key,shareHref(item));else window.open(shareHref(item),'_blank','noopener')}))};
  const render=()=>{const list=items.filter(i=>match(i,current));grid.innerHTML=list.length?list.map(i=>{const source=externalSource(i);return `<article class="news-card" data-story="${esc(storyKey(i))}"><div class="news-card-media" style="${i.image?`background-image:linear-gradient(180deg,rgba(2,7,13,.04),rgba(2,7,13,.18)),url('${esc(i.image)}')`:''}"></div><div class="news-card-body"><div class="news-card-meta"><span>${esc(i.source||'Source')}</span><span>•</span><span>${ago(i.publishedAt)}</span>${i.category?`<span>•</span><span>${esc(i.category)}</span>`:''}</div><h2><a href="${esc(storyUrl(i))}">${esc(i.title)}</a></h2><p>${esc((i.summary||'').slice(0,260))}${(i.summary||'').length>260?'…':''}</p><div class="news-card-actions"><button class="news-share-linkedin" type="button" data-smart-share data-story="${esc(storyKey(i))}" aria-label="Partager cet article Quantic News sur LinkedIn avec optimisation">in&nbsp; Partager</button><a class="news-source-link" href="${esc(storyUrl(i))}">Lire sur Quantic News →</a>${source?`<a class="news-source-original" href="${esc(source)}" target="_blank" rel="noopener">Source originale ↗</a>`:''}</div></div></article>`}).join(''):'<div class="news-empty">Aucune actualité technologique ne correspond à ce filtre pour le moment.</div>';wireSmartShare();focusDeepLink()};
  filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.filter||'all';render()}));
  async function loadFeed(){let lastError;for(const url of FEEDS){try{const r=await fetch(`${url}${url.includes('?')?'&':'?'}v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`feed_${r.status}`);const data=await r.json();if(!Array.isArray(data.items))throw new Error('bad_feed');return data}catch(e){lastError=e}}throw lastError||new Error('feed')}
  loadFeed().then(data=>{items=(data.items||[]).filter(eligible).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,60);if(deepLink&&!items.some(i=>storyKey(i)===deepLink)){const extra=(data.items||[]).find(i=>storyKey(i)===deepLink);if(extra)items.unshift(extra)}updated.textContent=data.updatedAt?`${items.length} actus tech · mis à jour ${ago(data.updatedAt)}`:`${items.length} actus tech`;render()}).catch(()=>{updated.textContent='Flux indisponible';grid.innerHTML='<div class="news-empty">Impossible de charger le flux Quantic News pour le moment. Réessaie dans quelques minutes.</div>'});
})();
