(()=>{
  const FEEDS=['./news/feed.json','https://raw.githubusercontent.com/XDSawyerLoL/LEFILLIBRE/main/feed.json','https://xdsawyerlol.github.io/LEFILLIBRE/feed.json'];
  const MANIFEST='./news/articles/index.json';
  const SITE='https://xdsawyerlol.github.io/QuanticSillage/news.html';
  const grid=document.getElementById('news-grid');
  const updated=document.getElementById('news-updated');
  const filters=[...document.querySelectorAll('.news-filter')];
  if(!grid)return;
  let items=[],current='all',articleMap=new Map();
  const esc=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const ago=iso=>{const d=new Date(iso),m=Math.max(0,Math.round((Date.now()-d)/60000));if(!Number.isFinite(m))return'';if(m<60)return`${m} min`;const h=Math.floor(m/60);if(h<24)return`${h} h`;return d.toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})};
  const hay=i=>`${i.category||''} ${i.source||''} ${i.title||''} ${i.summary||''}`.toLowerCase();
  const eligible=i=>/\bia\b|intelligence artificielle|artificial intelligence|openai|chatgpt|anthropic|gemini|mistral|robot|tech|numéri|logiciel|cyber|cloud|ordinateur|smartphone|innovation|startup|internet|data|automatisation|quantique|hardware|software|processeur|plateforme|application|apple|google|microsoft|nvidia|amd|intel|tesla|spacex/.test(hay(i));
  const match=(i,f)=>{const h=hay(i);if(f==='all')return true;if(f==='ai')return /\bia\b|intelligence artificielle|openai|chatgpt|anthropic|gemini|mistral|machine learning|modèle|agent|cloud|cyber|logiciel/.test(h);if(f==='robot')return /robot|robotique|androïde|humanoïde|automatisation|drone/.test(h);if(f==='product')return /produit|app|application|smartphone|iphone|android|ordinateur|navigateur|browser|logiciel|plateforme|device|apple|google|microsoft|nvidia|amd|intel/.test(h);if(f==='future')return /innovation|futur|recherche|prototype|startup|laboratoire|quantique|espace|énergie|mobilité|spacex|tesla/.test(h);return true};
  const story=i=>String(i.url||i.articleUrl||i.title||'');
  const page=i=>articleMap.get(story(i))||`${SITE}?story=${encodeURIComponent(story(i))}`;
  const source=i=>{const u=String(i.url||'').trim();return u&&!/xdsawyerlol\.github\.io\/LEFILLIBRE/i.test(u)?u:''};
  const json=async u=>{const r=await fetch(`${u}${u.includes('?')?'&':'?'}v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));return r.json()};
  const feed=async()=>{for(const u of FEEDS){try{const d=await json(u);if(Array.isArray(d.items))return d}catch{}}throw Error('feed_unavailable')};
  const manifest=async()=>{try{const d=await json(MANIFEST);articleMap=new Map((d.items||[]).map(x=>[String(x.story||''),String(x.url||'')]).filter(x=>x[0]&&x[1]))}catch{articleMap=new Map()}};
  const render=()=>{const list=items.filter(i=>match(i,current));grid.innerHTML=list.length?list.map(i=>`<article class="news-card"><a class="news-card-media" href="${esc(page(i))}" style="${i.image?`background-image:linear-gradient(180deg,rgba(2,3,6,.08),rgba(2,3,6,.22)),url('${esc(i.image)}')`:''}"></a><div class="news-card-body"><div class="news-card-meta"><span>${esc(i.source||'Source')}</span><span>•</span><span>${ago(i.publishedAt)}</span>${i.category?`<span>•</span><span>${esc(i.category)}</span>`:''}</div><h2><a href="${esc(page(i))}">${esc(i.title)}</a></h2><p>${esc((i.summary||'').slice(0,260))}${(i.summary||'').length>260?'…':''}</p><div class="news-card-actions"><a class="news-source-link" href="${esc(page(i))}">Lire l’article →</a>${source(i)?`<a class="news-source-original" href="${esc(source(i))}" target="_blank" rel="noopener noreferrer">Source originale ↗</a>`:''}</div></div></article>`).join(''):'<div class="news-empty">Aucune actualité ne correspond à ce filtre pour le moment.</div>'};
  filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');current=b.dataset.filter||'all';render()}));
  Promise.all([feed(),manifest()]).then(([d])=>{items=(d.items||[]).filter(eligible).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)).slice(0,60);if(updated)updated.textContent=d.updatedAt?`${items.length} actus tech · mis à jour ${ago(d.updatedAt)}`:`${items.length} actus tech`;render()}).catch(()=>{if(updated)updated.textContent='Flux indisponible';grid.innerHTML='<div class="news-empty">Impossible de charger Quantic News pour le moment. Actualisez la page.</div>'});
})();
